version: "3.7"

services:
  api:
    build:
      context: ./containers/api
      dockerfile: Dockerfile
    volumes:
      - "./containers/api:/app"
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=api.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@api-db:5432/api_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@api-db:5432/api_test
      - SECRET_KEY=super_secret_key
