version: "3.7"

services:
  api:
    build:
      context: ./containers/api
      dockerfile: Dockerfile
    volumes:
      - "./containers/api:/app"
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=api.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@api-db:5432/api_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@api-db:5432/api_test
      - SECRET_KEY=super_secret_key
    depends_on:
      - api-db

  api-db:
    build:
      context: ./containers/api-db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  next-js:
    build:
      context: ./containers/next-js
      dockerfile: Dockerfile
    volumes:
      - "./containers/next-js:/app"
      - "/app/node_modules"
      - "/app/.next"
    ports:
      - 3007:3000
    environment:
      - NODE_ENV=development
    depends_on:
      - api

  nginx:
    build:
      context: ./containers/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - api
      - next-js
