"""empty message

Revision ID: 538fff1112be
Revises: 
Create Date: 2019-12-02 20:06:03.343269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '538fff1112be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
